### ISSUE TITLE
Swift package manager 

### ISSUE THREAD

**Issue by jigar007** [twilio/conversations-ios#1]
Is there any way I can add conversations to project via SPM? Currently, I am using TwilioConversationsClient via cocoa pods and that's the only dependency which is not available via SPM in my entire project.

**Comment by Gray-Wind** [comment]
Currently there is no such possibility, but we are working on it, I will let you know once we support SPM.

**Comment by berkus** [comment]
Cross-reference https://github.com/twilio/twilio-chat-ios/issues/16

**Comment by borut-t** [comment]
Any news on this end?

**Comment by Gray-Wind** [comment]
Hello,

We've just published new 1.3.0 version with SPM support!
