### ISSUE TITLE
Unable to use the Join function

### ISSUE THREAD

**Issue by mweyamutsvene** [twilio/conversations-ios#10]
`- (void)joinWithCompletion:(nullable TCHCompletion)completion` Is this function just a left over function from the Programmable Chat Api? 

I would love the feature to be able to join a conversation with a given sid, but unfortunately I cannot fetch a conversation using the `conversationWithSidOrUniqueName:completion:` if I haven't yet joined the conversation, which kind of makes the preceding call superfluous.  According to the docs, I shouldn't be able to add a participant without using a backend service to do so.

**Comment by Gray-Wind** [comment]
Hello!

You can join to the newly created conversation. That is the purpose of the method.

With `conversationWithSidOrUniqueName:completion:` it is possible to query conversations visible to `superadmin` role, which is not so common case in the SDK, but still we have this ability.
