### ISSUE TITLE
Going in and out of airplane mode fails to reconnect

### ISSUE THREAD

**Issue by mweyamutsvene** [twilio/conversations-ios#11]
On Version 1.3.0, when you toggle airplane mode TwilioConversationsClient fails to reconnect, resulting in the final TCHClientConnectionState being `TCHClientConnectionStateError`

While the device is in offline mode, the stated updates to `TCHClientConnectionStateDisconnected` 
 -> `TCHClientConnectionStateConnecting` and it takes a bit of time before it finally lands on `TCHClientConnectionStateError`

**Comment by Gray-Wind** [comment]
Hello, thank you for the report. Please check on version 1.3.1, this bug should be fixed there.
