### ISSUE TITLE
Carthage + xcframework

### ISSUE THREAD

**Issue by ealbizzati** [twilio/conversations-ios#12]
## Description
The SDK is now distributed as an xcframework, and due to that, Carthage support was paused. However, Carthage 0.38.0 supports binary xcframeworks.

## Steps to Reproduce
Open https://github.com/twilio/conversations-ios/blob/master/twilio-convo-ios.json
Check for an xcframework in the format that Carthage expects

## Expected Behavior
An xcframework to be present

## Actual Behavior
Only .frameworks are in the JSON

## Reproduces How Often
Always

## Same problem reported by https://github.com/marcelofabri here https://github.com/twilio/twilio-chat-ios/issues/32

**Comment by joeydong** [comment]
any updates? it's disappointing that [Twilio voice](https://github.com/twilio/twilio-voice-ios/issues/78) fixed support for `Carthage + xcframeworks` so promptly but not this repo.

**Comment by Pavel-Cherentsov** [comment]
Hi @joeydong & @ealbizzati.
Carthage + xcframeworks support not done yet, we keep this in mind, will fix & check it as soon as possible.

**Comment by Gray-Wind** [comment]
Hello, we plan to return Carthage support with the next major release.

**Comment by Gray-Wind** [comment]
We have spent some time on enabling Carthage anew, but with limited resource didn't manage to find a way to support a binary dependency with binary subdependencies. Maybe we will have more time to solve the issue in the future, cannot give any estimations tho.

**Comment by berkus** [comment]
Closing, no resources to work on this.
