### ISSUE TITLE
Connection takes time  iOS Swift

### ISSUE THREAD

**Issue by aiyub007** [twilio/conversations-ios#13]
Hi 
When I connect to client using below code  :: 

```
TwilioConversationsClient.conversationsClient(withToken: token,
         properties: nil,
         delegate: self) { (result, client) in
           self.client = client      
            }
 }
```
It takes time when there are more then 100 conversations

When I checked code, I got to know the connection obj client has conversation obj

Please give the resolutions . There must be pagination for the conversations. and connection obj stand alone connects rather then fetching conversations with it.

Thanks in advance.

**Comment by Pavel-Cherentsov** [comment]
Hello! 
Yes, Conversations Client on its init performs fetching and synchronising of all conversations the current user participates.
So the more conversations - the longer init time.
How long is it in your case?

**Comment by jayanth1991** [comment]
@Pavel-Cherentsov I am @aiyub007 colleague, it takes anywhere between 8-10s and its pretty consistent in terms of the time it takes.

We expect there to be over 500+ conversations a single user could be subscribed to at any given time (mostly 1-1 DMs). Please advice.

**Comment by Pavel-Cherentsov** [comment]
Hi @jayanth1991, 
Well, such initialisation time looks as expected.
Yes, with 500+ conversations it will be even some longer...
In future we are going to speed up init on hundreds/thousands of conversations, can't provide no promises yet.

**Comment by jayanth1991** [comment]
Hi @Pavel-Cherentsov its not a future problem, its actually happening right now for us and unless there is a workaround for this issue, its practically unusable under normal user behavior

**Comment by Gray-Wind** [comment]
Hello, we've made some optimizations and the client should behave better in cases of high loads. Could you check it now?

**Comment by Gray-Wind** [comment]
I'm closing the ticket since there is no more comment on this topic. Feel free to create a new issue.
