### ISSUE TITLE
Crash on version 2.0.3

### ISSUE THREAD

**Issue by ryanisnhp** [twilio/conversations-ios#17]
Hi guys, I use the latest version of TwilioConversation (2.0.3) and sometimes it crash when I first open my app
![image](https://user-images.githubusercontent.com/26299033/147185212-9520289a-8058-449f-9240-8033af658648.png)
Can you help me check this.
Thanks in advance

**Comment by Pavel-Cherentsov** [comment]
Hi @ryanisnhp,
Thank you for reporting the issue.
Looks like Client emergency shutdown..
We are investigating that and will fix.

**Comment by rusmonster** [comment]
Hi! @ryanisnhp,
Do you keep strong reference to the TwilioConversationsClient in your app? It looks like the Client is destroyed while registering notification token, because of no strong references to it.

**Comment by ryanisnhp** [comment]
I see, I will update my code again and will check if the crash will be solved. thanks bro

**Comment by Gray-Wind** [comment]
I'm closing the issue as no answer provided. Feel free to open a new ticket.
