### ISSUE TITLE
TwilioConversationsClient via POD has been installed and working in 1 project but not working in an other project.

### ISSUE THREAD

**Issue by zahoorahmadgorsi** [twilio/conversations-ios#18]
Hi,

I am having 2 projects and both are developed using Xcode 12.4. One project I had created couple of months ago and used TwilioConversationsClient (pod 'TwilioConversationsClient', '2.1') and its working fine even now. But tomorrow I created a new project and installed TwilioConversationsClient using same version (pod 'TwilioConversationsClient', '2.1') but its not working. 

I am getting the following error 

Failed to build module 'TwilioConversationsClient' from its module interface; the compiler that produced it, 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)'

Any solution other than to use Xcode 13 as that is not possible for me so quickly. Please.

**Comment by Gray-Wind** [comment]
Hello!

There is not much we can do right now, as we cannot build the SDK with Xcode 12 at the moment. We are trying to update Xcode version not so eagerly, only when needed for internal development, sorry for the inconvenience.

As for the reason why the old project works, but the new one is not, it could be possible that you did update your pod file, but never actually installed new version of the SDK. I cannot find any other reason.

**Comment by Gray-Wind** [comment]
Hello again!

I continued looking into the issue and found out that we mistakenly forgot to enable Library Evolution.

I will try to push the issue forward and provide the working solution in a short time.

**Comment by zahoorahmadgorsi** [comment]
Hello!!

Thanks for the response. Hopefully it will resolve the issue, please let me know when its done.

**Comment by Gray-Wind** [comment]
Hello, we made couple releases now and the issue must be fixed. Could you check please?

**Comment by Gray-Wind** [comment]
Closing as no answer provided.
