### ISSUE TITLE
App crashes while trying to update twilio token

### ISSUE THREAD

**Issue by rtavares89** [twilio/conversations-ios#19]
Hi,

I'm facing some crashes when app tries to update Twilio token. This mainly happens when app is in background for 1 or 2 days and when it came back to foreground it crashes after a few seconds. After analysing the issue, we suspect that this is due to while the app is trying to get internet connection, Twilio is trying to update the token without internet connection. While analysing this behaviour I've found out that memory is increasing a lot, as you can see on screenshots, and after reaching a threshold it kills the app. It seems that it is suck creating websockets in a loop, creating in a few seconds more than 10000 websockets instances.

I read and implemented your best practices suggestions in order to discard that the implementation was wrong. 
Can you check if this is a bug on your side or is there anything we can do to mitigate this behaviour?

I'm using the latest SDK version (2.1.0) and I have some logs that I can attach if needed.

Thanks!

Memory: 
<img width="287" alt="Screenshot 2022-02-01 at 18 04 58" src="https://user-images.githubusercontent.com/26629002/152025204-52ab05f6-d9d3-4d33-8752-d249ffbe63fb.png">

Twilio Conversations SDK websockets instances:
<img width="531" alt="Screenshot 2022-02-01 at 18 05 55" src="https://user-images.githubusercontent.com/26629002/152025353-98b57117-5be7-47b8-80b7-0149992808cb.png">

**Comment by Pavel-Cherentsov** [comment]
Hi @rtavares89, many thanks for your investigation, 
looks like TCHWebSocketDelegate instances leaking and overflowing..

Yes, logs would be very helpful, kindly asking to attach. 
Debug or trace level would be best (if possible).

Is issue reproducible on iOS 13+ or on pre-13?

**Comment by rtavares89** [comment]
Hi @Pavel-Cherentsov,

Is it possible to send you the logs privately? I tried to use your support email (support@twilio.com) but I'm not able to send it due to email size. (logs just have 2.6mb)

**Comment by Gray-Wind** [comment]
Could you send logs with [a support ticket](https://support.twilio.com/hc/en-us/requests/new)? You can add also a link to this issue so it would be tracked easier.

**Comment by rtavares89** [comment]
Hi @Gray-Wind,

Just submitted a support ticket with number # 7862815. Thanks

**Comment by Gray-Wind** [comment]
Sorry for the long response, we are looking into the issue. We have some understanding of what is going on, no estimates though on the release with the fix. Future communications with you regarding this issue will be held via the support ticket.

Meanwhile you can rely on reachability and not update token while the device is offline, in this case the issue won't be triggered. I will keep this ticket alive until we release the fix.
