### ISSUE TITLE
Deployed demo

### ISSUE THREAD

**Issue by iBobik** [twilio/conversations-ios#2]
Is there some demo app where I can try the experience? Or some apps build with this SDK you could dislose and I can find and the App Store?

**Comment by Gray-Wind** [comment]
Hi!

At the moment there is no dedicated demo application at the moment, we are working on it. 

Meanwhile you could take a look to the [Chat Demo App](https://github.com/twilio/twilio-chat-demo-ios/) and [special branch](https://github.com/twilio/twilio-chat-demo-ios/tree/feature/migrate-to-conversations-sdk) with migration commits from Chat SDK to Conversations SDK, which is not perfect, but will give some understatement how to use it.

**Comment by iBobik** [comment]
Thank you for reply.

For now I need some real app to evaluate UI with our stakeholders. If Chat
SDK will be soon the same from users perspective, it could be enough.

We just need something to compare with competitors to evaluate how much
development it would need.


Honza Pobořil

**Comment by Gray-Wind** [comment]
Hello,

I am sorry, I've totally forgot to update the ticket, we have a demo application now, you can check it out here: https://github.com/twilio/twilio-conversations-demo-ios-swift
