### ISSUE TITLE
Crash +[TCHHelpers mainQueueOrQueue:], file TCHHelpers.mm, line 268

### ISSUE THREAD

**Issue by khanhson47** [twilio/conversations-ios#21]
Hi,

I'm facing crashes when app tries to get conversation last message 
```
func getLastMessages(withCount count: UInt, completion: @escaping TCHMessagesCompletion)
```
after calling below function to get Twilio client
```
class func  TwilioConversationsClient.conversationsClient(withToken token: String, properties: TwilioConversationsClientProperties?, delegate: TwilioConversationsClientDelegate?, completion: @escaping TCHTwilioClientCompletion)
```

![Screen Shot 2022-03-22 at 18 14 26](https://user-images.githubusercontent.com/63218181/159472090-01ef8d23-cf53-4d50-9a60-aeff7b759dfb.png)

The log wrote `Assertion failed: (queue), function +[TCHHelpers mainQueueOrQueue:], file TCHHelpers.mm, line 268.`, but I tried to run it on many kinds of thread it stills crash. 

What this crash is about? Is it said that we must run on specific thread?
Do you know any solution for this?

Thanks

**Comment by Gray-Wind** [comment]
Hello!

What is the version of the SDK you use?

**Comment by khanhson47** [comment]
Hi Gray,

  - TwilioAccessManager (1.1.2)
  - TwilioConversationsClient (2.2.0)

**Comment by Gray-Wind** [comment]
First of all, remove `TwilioAccessManager` dependency, it is deprecated. All the token lifecycle management is included in the Conversations SDK.

Second, thank you, we will take a deeper look into the issue, it should not happen ever. Could you in the meanwhile check the issue on 2.2.1?

**Comment by khanhson47** [comment]
```
```

**Comment by khanhson47** [comment]
```
Could you in the meanwhile check the issue on 2.2.1?
```
It still crash on 2.2.1

**Comment by Gray-Wind** [comment]
Thank you for the report! I would like to ask you to create [a support ticket](https://support.twilio.com/hc/en-us/requests/new) with [logs](https://www.twilio.com/docs/conversations/error-handling-diagnostics#ios-logging-objective-c-or-swift) of the reproduction (set please `trace` level), so I can understand what is going on. Add a link to the GitHub issue, so it will come back to me faster.

**Comment by Gray-Wind** [comment]
Hello, version 2.2.2 with the fix has been released. Thank you for the report!
