### ISSUE TITLE
When TCHUser offline & online status update delegate method never been called

### ISSUE THREAD

**Issue by kalebupatan7** [twilio/conversations-ios#22]
<img width="674" alt="Screenshot 2022-04-22 at 3 40 23 PM" src="https://user-images.githubusercontent.com/59355434/164726352-532075d3-f8f8-49c5-b1a6-f3a550990d21.png">

TCHConversationDelegate has conversationsClient(_ client: TwilioConversationsClient, user: TCHUser, updated: TCHUserUpdate) method.

When ever other TCHUser change his status from offline to online, vice versa. This method has to be called, but it's not being called.

Except this method, remaining all methods are being called in TCHConversationDelegate.

Note: I enabled reachability indicator in Console.

Please let me know why this method is not being called.

**Comment by kalebupatan7** [comment]
> Hi @kalebupatan7! How do you make _TCHUser_ change his status from online to offline and back? Client re-creation or network disconnection/reconnection?

Hi @Pavel-Cherentsov , I made TCHUser change his status from online to offline by shutdown client and from offline to online by re-creation of client.

**Comment by Pavel-Cherentsov** [comment]
Could you please ensure client is subscribed to `TCHUser` updates  ([user [isSubscribed](https://media.twiliocdn.com/sdk/ios/conversations/releases/2.2.2/docs/Classes/TCHUser.html#//api/name/isSubscribed)] returns `YES`) ?
Do you get `TCHUser` by use of [subscribedUserWithIdentity:completion:](https://media.twiliocdn.com/sdk/ios/conversations/releases/2.2.2/docs/Classes/TwilioConversationsClient.html#//api/name/subscribedUserWithIdentity:completion:) ?
Could you maybe provide your code sample?

**Comment by kalebupatan7** [comment]
@Pavel-Cherentsov , I checked TCHUser updates ([user [isSubscribed](https://media.twiliocdn.com/sdk/ios/conversations/releases/2.2.2/docs/Classes/TCHUser.html#//api/name/isSubscribed)] returns YES)
Even I get TCHUser by use of [subscribedUserWithIdentity:completion:](https://media.twiliocdn.com/sdk/ios/conversations/releases/2.2.2/docs/Classes/TwilioConversationsClient.html#//api/name/subscribedUserWithIdentity:completion:) 
But conversationsClient(_ client: TwilioConversationsClient, user: TCHUser, updated: TCHUserUpdate) method is not calling

**Comment by berkus** [comment]
Closing, no interactions and versions have been updated since then.
