### ISSUE TITLE
Crash when I try to send text message and call buildAndSend()

### ISSUE THREAD

**Issue by nshape-dev** [twilio/conversations-ios#24]
I'm using pod 'TwilioConversationsClient', '~> 2.2', whenever I try to send a message with this link of code 
`self.conversation?.prepareMessage().setBody("Hello").buildAndSend()`

The app crashs in this method `[TCHConversationLimits initWithConversationLimitsInternal:]`

![Screenshot 2022-05-31 at 3 51 16 pm](https://user-images.githubusercontent.com/98820070/171189875-8f83a8e1-d538-4f2f-b438-b55fe6ad83bd.png)

![Screenshot 2022-05-31 at 4 15 21 pm](https://user-images.githubusercontent.com/98820070/171195062-06ffeafd-0491-42fe-9a39-0fbcfc24e1a6.png)

**Comment by Pavel-Cherentsov** [comment]
Hi @nshape-dev, thank you for reporting.
I suppose that such crash could happen if message is attempted to be sent at the same time the Client is shutting down.
We are applying a fix for this case.

**Comment by Gray-Wind** [comment]
Hello, this issue has been fixed in the new release.
Feel free to create a new issue if something doesn't work.
