### ISSUE TITLE
Crash [TwilioConversationsClient was compiled with optimization]

### ISSUE THREAD

**Issue by mmmcompanies** [twilio/conversations-ios#25]
TwilioConversationsClient was compiled with optimization - stepping may behave oddly; variables may not be available.

When add media --- .addMedia(data: ......... )

TwilioConversationsClient (2.2.2)

Xcode :- Version 13.3.1 (13E500a) 
OS - macos monterey 12.3.1
chip -- Apple M1
![Screen Shot 2022-06-21 at 10 14 06 AM](https://user-images.githubusercontent.com/18510500/174718105-99e680a4-dcee-4b4d-b146-a69fa79b177a.png)
![Screen Shot 2022-06-21 at 10 12 25 AM](https://user-images.githubusercontent.com/18510500/174718119-6f52f76c-2071-4589-a893-1c09f74d553a.png)
![Uploading Screen Shot 2022-06-21 at 10.11.47 AM.png…]()

**Comment by Pavel-Cherentsov** [comment]
Hi @mmmcompanies! 
How often does it crash?
Is it reproducible without optimization?
Are you running app on simulator or device?
Could you please provide crash report and/or debug logs (with `TCHLogLevelDebug` or `TCHLogLevelTrace` level)?

**Comment by mmmcompanies** [comment]
Hi @Pavel-Cherentsov 
I am running app on device. 
I deeply research on this issue and found the solution. 

It happened  because we shutdown the Twilio Client before call the add media --- .addMedia(data: ......... )  function. 
So we check the client shutdown or active then apply all action. 

Thanks
