### ISSUE TITLE
Did you remove Cocoa Pods support?

### ISSUE THREAD

**Issue by jhicks-ddm** [twilio/conversations-ios#26]
I'm trying to update to the latest 2.2.4 release but Cocoa Pods is saying it can't find it. Also, doesn't look like any of the code is in the repo now. Not sure what is going on. Thanks!

**Comment by jhicks-ddm** [comment]
Looks like I just needed to add `source 'https://github.com/CocoaPods/Specs'` to my Pods file. Not sure why it was working before without it.

**Comment by Pavel-Cherentsov** [comment]
...or `source 'https://cdn.cocoapods.org/'` - to avoid full cocoapods repo cloning and make first `pod install` a bit faster.
