### ISSUE TITLE
Error accessing remote repository while updating conversation-ios package to version 3.0.0

### ISSUE THREAD

**Issue by anish190** [twilio/conversations-ios#34]
I am trying to update the conversation-ios package to version 3.0.0, but I am getting the following error:

> https://github.com/twilio/twilsock-ios: The remote repository could not be accessed. Make sure a valid repository exists at the specified location and that the correct credentials have been supplied.

Environment:
TwilioConversationsClient v3.3.0

**Comment by RicardoNunoAlmeida** [comment]
@anish190: we are very sorry for this. We'll set up access to [that repo](https://github.com/twilio/twilsock-ios) and ping you as soon as it is completed.

**Comment by RicardoNunoAlmeida** [comment]
Hey @anish190 can you please try again now and let us know how it goes?

**Comment by anish190** [comment]
Hi @RicardoNunoAlmeida,
 Thanks for the update. Unfortunately, I am getting another error.

invalid custom path 'Dummy' for target 'TwilioConversationsClientTarget'

**Comment by Gray-Wind** [comment]
Hello @anish190,

I've just re-published the release, could you please try again?

**Comment by anish190** [comment]
@Gray-Wind ,
 I am able to compile the project when I directly add `conversation-ios` to Package dependencies in Xcode. But I want to add it as a dependency to my custom package. I am getting the same error when I add it as a dependency.

> invalid custom path 'Dummy' for target 'TwilioConversationsClientTarget'

ChatKit
//Package.swift
```
...
...
dependencies: [
        // Dependencies declare other packages that this package depends on.
        .package(url: "https://github.com/twilio/conversations-ios", from: Version(3, 0, 0))
       ]
...
...
.target(
            name: "ChatKit",
.product(name: "TwilioConversationsClient", package: "conversations-ios"),
])
```

**Comment by Gray-Wind** [comment]
Hi @anish190,

Sorry to ask, but did you try to reset SPM caches?

**Comment by Gray-Wind** [comment]
@anish190 glad to hear that! Do I understand correctly that now it all works fine and this ticket could be closed?
