### ISSUE TITLE
New Crash after Integrating Library 3.1.0

### ISSUE THREAD

**Issue by epyifany** [twilio/conversations-ios#38]
Hi Twilio Team,
We saw a new crash in our app after integrating the latest version of the Twilio conversations library. 

Introduced this crash in our Application:

Version:16.4.1

# Crashlytics - Stack trace

EXC_BAD_ACCESS (KERN_INVALID_ADDRESS)

com.apple.main-thread
0  libsystem_kernel.dylib         0xda8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13a1c mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13c5c mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x12ec mach_msg + 24
4  CoreFoundation                 0x7aac4 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd08 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80eb0 CFRunLoopRunSpecific + 612
7  GraphicsServices               0x1368 GSEventRunModal + 164
8  UIKitCore                      0x3a1668 -[UIApplication _run] + 888
9  UIKitCore                      0x3a12cc UIApplicationMain + 340
10 ...                    0x5738 main + 13 (main.swift:13)
11 ???                            0x1c97d8960 (Missing)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xda8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13a1c mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13c5c mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x12ec mach_msg + 24
4  CoreFoundation                 0x7aac4 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd08 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80eb0 CFRunLoopRunSpecific + 612
7  Foundation                     0x42054 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x41f3c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x4d66a4 -[UIEventFetcher threadMain] + 436
10 Foundation                     0x5b518 __NSThread__start__ + 716
11 libsystem_pthread.dylib        0x16cc _pthread_start + 148
12 libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x167c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  libc++.1.dylib                 0xcacc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  NewRelic                       0x84dc0 NewRelic::NRMALoggerBridge::log(unsigned int, char const*, unsigned int, char const*, char const*, char*) + 101568
4  NewRelic                       0x85344 NewRelic::NRMALoggerBridge::log(unsigned int, char const*, unsigned int, char const*, char const*, char*) + 102980
5  NewRelic                       0x854e4 NewRelic::NRMALoggerBridge::log(unsigned int, char const*, unsigned int, char const*, char const*, char*) + 103396
6  libsystem_pthread.dylib        0x16cc _pthread_start + 148
7  libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x167c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  libc++.1.dylib                 0xcacc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  NewRelic                       0x84dc0 NewRelic::NRMALoggerBridge::log(unsigned int, char const*, unsigned int, char const*, char const*, char*) + 101568
4  NewRelic                       0x85344 NewRelic::NRMALoggerBridge::log(unsigned int, char const*, unsigned int, char const*, char const*, char*) + 102980
5  NewRelic                       0x854e4 NewRelic::NRMALoggerBridge::log(unsigned int, char const*, unsigned int, char const*, char const*, char*) + 103396
6  libsystem_pthread.dylib        0x16cc _pthread_start + 148
7  libsystem_pthread.dylib        0xba4 thread_start + 8

**Comment by Gray-Wind** [comment]
Hello,

The release with the fix just been released. Feel free to open a new ticket.
