### ISSUE TITLE
CocoaPods could not find compatible versions for pod "TwilioConversationsClient" 4.0

### ISSUE THREAD

**Issue by epyifany** [twilio/conversations-ios#39]
From the twilio Docs, it suggest that TwilioConversationsClient is still available as a cocoapod
 https://www.twilio.com/docs/conversations/sdk-download-install 

I received the following error during our implementation 

[!] CocoaPods could not find compatible versions for pod "TwilioConversationsClient":
  In Podfile:
    TwilioConversationsClient (~> 4.0)

None of your spec sources contain a spec satisfying the dependency: `TwilioConversationsClient (~> 4.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by Gray-Wind** [comment]
Hello,

Thank you for reaching out, do you mind to share what `pod search TwilioConversationsClient` returns in your case?

I can see that 4.0.0 is available
```
-> TwilioConversationsClient (4.0.0)
   Twilio Conversations Client
   pod 'TwilioConversationsClient', '~> 4.0.0'
```

Also you can try to do `pod repo update` to see if the version would appear for you.

**Comment by epyifany** [comment]
That worked for me! Thank you guys for the continuous updates!
