### ISSUE TITLE
Mac Catalyst Support

### ISSUE THREAD

**Issue by mweyamutsvene** [twilio/conversations-ios#4]
Doesn't look like Mac Catalyst is currently supported: 
`building for Mac Catalyst, but linking in dylib built for iOS Simulator, file '.../TwilioConversationsClient/TwilioConversationsClient.framework/TwilioConversationsClient' for architecture x86_64`

Is Twilio planning on supporting this feature?

**Comment by Gray-Wind** [comment]
Hello!

Thank you for reaching out. It is a work in progress and will be published soon.

**Comment by Gray-Wind** [comment]
Hello,

We have published Conversations SDK with version 1.3.0, which supports XCFramwork and SPM. We almost ready to support Mac Catalyst as well. Right now we are looking for customers for pilot version. Could you please [contact support](https://support.twilio.com/hc/en-us/requests/new)?
