### ISSUE TITLE
Cant use LLDB after upgrading to 4.0.2

### ISSUE THREAD

**Issue by tomerhy** [twilio/conversations-ios#44]
warning: Swift error in scratch context: error: failed to load module 'App_Name'
.
Shared Swift state for 'App_Name' has developed fatal errors and is being discarded.
REPL definitions and persistent names/types will be lost.

error: expression failed to parse:
unknown error

on 4.0.0 it works, I have xcode 14.3.1  mac book pro Apple M1 Max

**Comment by berkus** [comment]
Dup of #42
