### ISSUE TITLE
Not existing dependency version for twilsock-ios 

### ISSUE THREAD

**Issue by vladdorfman** [twilio/conversations-ios#50]
https://github.com/twilio/conversations-ios/blame/339fe3aad6e0a65fac16fc97d3fcf7a10ecc142e/Package.swift#L18C3-L18C3

This update is problematic, because there is no version  2.0.4 for this dependency:
https://github.com/twilio/twilsock-ios/tags

Gives this error:
Dependencies could not be resolved because no versions of 'twilsock-ios' match the requirement 2.0.4..<3.0.0 and 'conversations-ios' depends on 'twilsock-ios' 2.0.4..<3.0.0.

**Comment by berkus** [comment]
Hi, I've created the missing tags, sorry about that.
