### ISSUE TITLE
Error when adding via Swift Package Manager

### ISSUE THREAD

**Issue by tonydaly** [twilio/conversations-ios#6]
When adding via SPM I receive this error:

`target 'TwilioConversationsClient' referenced in product 'TwilioConversationsClient' could not be found`

<img width="729" alt="Screenshot 2021-03-29 at 11 43 50" src="https://user-images.githubusercontent.com/68354/112825894-36899080-9084-11eb-9f27-8c4915e2c01e.png">

I've tried this on a completely new project and still see the same error. Even when adding the `-ObjC` flag.

This is on Xcode Version 12.4 (12D4e).

Really looking forward to using SPM rather than CocoaPods for this, thanks for this!

**Comment by Gray-Wind** [comment]
I've fixed the issue. You may need to reset SPM caches and/or restart Xcode to make it work again.
